title: Loic Coyle
theme: ["PaperMod"]

params:
  env: production
  author: Loic Coyle
  defaultTheme: dark

  profileMode:
    enabled: true
    title: "Loic Coyle" # optional default will be site title
    subtitle: "☢️ Nuclear Engineer | 🖥️ Software Dev | 🧠 ML Engineer | 💡 Data Scientist | 🐧 Lunix nerd"
    imageUrl: "<image link>" # optional
    imageTitle: "Profile Image" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    # buttons:
    # - name: Archive
    #   url: "/archive"
    # - name: Github
    #   url: "https://github.com/loiccoyle"

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/loiccoyle"
    - name: "linkedin"
      url: "https://linkedin.com/in/loiccoyle"
